### ISSUE TITLE
About wifi & bluetooth module

### ISSUE THREAD

**Issue by 50553613** [marcello0201/Dell-5447-Hackintosh-Catalina-10.15.4-Update#1]
Thank you for sharing. I successfully turned on my laptop.
I still have a few puzzles. I hope you can help me solve them.
Is the Wifi & bluetooth module AR9565 or DW 1560? Are they the same or can they be driven with the same configuration?
Their prices vary a lot in our place.

**Comment by marcello0201** [comment]
Thanks for contacting, AR9565 is not supported, currently I use the Dell DW 1560 Wifi and Bluetooth module, this card works well on the Mac and on the inspiron 5447, this configuration is made to use the DW 1560, I recommend replacing your AR9565 with DW 1560.

**Comment by 50553613** [comment]
Thank you for your reply，the new Wifi & bluetooth module is working. :)
There is another trouble for me，what does “Iniciar com o sistema” mean？where should i put the “Jack fix” file in？
When I close the lid of the laptop,and then open it,  the creen is black, and I can't wake it up.How  can I fix that?

**Comment by marcello0201** [comment]
Great that your wifi & bluetooth is working :)

This "Iniciar com o sistema" means to access the System Preferences \ Users and Groups \ start items you add the file "Jack fix" there to start with the mac boot, this will correct the sound noise in the headphones.
In the case of the black screen this does not happen on mine, when I want to put it to sleep I go to the top bar of the apple and put sleep, after a while I press the power button and it wakes up perfectly without error, you forgot to put some repository file?

In case you can't solve it, I'll be releasing an EFI update to fix some things, I'll release this update in a new repository here on github with the new system update and you can get it later.

**Comment by 50553613** [comment]
That's very kind of you.

I put all of the kext files from yours，except “DisplayProductID-5f1”，because I can't confirm the right place  inside  “/System/Library/Displays/Contents/Resources/Overrides” 。
By the way, my cpu is Intel Core i5 - 4210U，I don't know why there are a variety of configurations.

I will try again later ，and hope everything goes well.

**Comment by marcello0201** [comment]
In the case of “DisplayProductID-5f1”, you must unzip the folder inside and place it in the directory / System / Library / Displays / Contents / Resources / Overrides
there other display folders, and just throw that folder there and that's it, I'll leave some links with pictures for you to base yourself on.

https://ibb.co/ZfXdkTj
https://ibb.co/kMm7hXT

Your core i5 has a base clock of 1.70Ghz, you must change it in config.plist using clover configurator on CPU \ Frenquency MHz from 2000 to 1700

In relation to sleep I fixed it as follows, I did a cpu fimware update to support hackintosh sleep, however if you do it wrong you may have problems, I will leave the link as I did, but "* AT YOUR OWN RISK *", this will resolve sleep on your Dell.

https://github.com/marcello0201/Dell-5547-Hackintosh/tree/master/Management-Engine-Firmware

If you need help and just ask.

**Comment by 50553613** [comment]
Sorry to bother you again.Could you show me the settings of BIOS?

**Comment by marcello0201** [comment]
No problem, you can ask for help if you need to.
Below is how mine is configured.

https://ibb.co/F79WBcs
https://ibb.co/TwFRLc7
https://ibb.co/SyXJYFh
https://ibb.co/yNWmrDz

The photos have the settings I use on my Inspiron 5447.

I customized the UEFI boot to be saved in dell, in the third photo there is an option to "add boot options" you create the custom boot name for the clover, I put "MacOS" as in the photo, in "View Boot Options Propeties" you you must add the File Patch, in the fourth photo you must type the command: start boot.efi at "disk name" ()
In my case the disk name is Macintosh SSD so the command is: start boot.efi at Macintosh SSD ()
Then just save in F10 and put it as the main boot.

**Comment by marcello0201** [comment]
New repository available, see: https://github.com/marcello0201/Dell-5447-Hackintosh-Catalina-10.15.5
